[MIPS] mips-jazz: correct flags for timer io resource
arch/mips/jazz/setup.c:55:4: error: Initializer entry defined twice

Signed-off-by: Alexey Dobriyan <adobriyan@gmail.com>
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit c4a3f55988ccf71ff530422b4678edcc9bcd6e1b)