[MIPS] I8253: Export i2853_lock to modules.
This fixes:

  ERROR: "i8253_lock" [drivers/input/misc/pcspkr.ko] undefined!

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 55e98e0afbe16e0b014aa424955f814c964aa4c3)